services:
  act:
    build:
      context: .
      dockerfile: .act/Dockerfile
    working_dir: ${REPOSITORY_ROOT}
    entrypoint: ["act"]
    privileged: true
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - .:${REPOSITORY_ROOT}
      - /var/run/docker.sock:/var/run/docker.sock
