[tools]
dotnet = "10.0.202"
node = "24"

[tasks.ui]
description = "Run frontend locally"
dir = "ui"
run = "npm run dev"

[tasks.be]
description = "Run backend locally"
dir = "be"
run = "dotnet run --project Cashregister.Api --configuration Debug"
env = { "ASPNETCORE_ENVIRONMENT" = "Production" }

[tasks.run]
description = "Run both frontend and backend locally"
run = [
  { tasks = ["be", "ui"] }
]

[tasks.compose]
description = "Run local docker-compose manifest"
run = "docker compose --file=docker-compose.local.yaml up --build --detach"
